# Generated by Django 6.0.5 on 2026-05-21 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
    ]
